### ISSUE TITLE
Needs manage server permissions to add to server

### ISSUE THREAD

**Issue by 0R61** [logicguy1/Discord-DM-All-Bot#3]
Since it is required to have manage server permissions. How is this usable?

**Comment by rahimprz** [comment]
**Drillienissen, did said it doesn't require we'll talk with him maybe he can answer this question.**

**Comment by verticalsync** [comment]
you need to have those permissions to add any bot to any server
but once its added it doesn't need any permissions to dm people which should be obvious.

**Comment by logicguy1** [comment]
I dont see your issue here? What is your problem?

**Comment by logicguy1** [comment]
@0R61
