### ISSUE TITLE
embed not work

### ISSUE THREAD

**Issue by thedtvn** [logicguy1/Discord-DM-All-Bot#5]
my embed
`{
    "content": "Notification",
    "embed": {
        "title": "BetMC Notification",
        "description": "**Server BetMC đang tổ chức giveaway với phần thưởng là :**\n**50,000 Cowoncy**\n**Tham gia ở kênh #🎉giveaway🎉 của BetMC để tham gia giveaway**\n",
        "color": 39129,
        "timestamp": "2021-09-18T12:01:16.936Z",
        "url": "",
        "author": {
            "name": ".",
            "url": "",
            "icon_url": ""
        },
        "thumbnail": {
            "url": ""
        },
        "image": {
            "url": "https://cdn.discordapp.com/attachments/863696180431945748/888605169791676447/T_Server_Invite_Background_1.png"
        },
        "footer": {
            "text": "Nếu bạn thấy phiền do tin nhắn này thì chúng tôi xin lỗi !",
            "icon_url": ""
        },
        "fields": []
    }
}`

**Comment by thedtvn** [comment]
![image](https://user-images.githubusercontent.com/80153297/133890098-256b0a46-6942-4986-9feb-08f16b3848b6.png)

**Comment by rahimprz** [comment]
The embed doesn't work, because the embed isn't formed properly.
